global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['<vm_ip>:9100']
  - job_name: 'backend'
    static_configs:
      - targets: ['<vm_ip>:5001']
